let loremBtn = document.getElementById('lorem');

loremBtn.addEventListener('click', insertLorem);

function insertLorem() {
    let textarea = document.querySelector('textarea');
    console.log(textarea.innerHTML);
    const lorem = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, iure ratione esse modi sint a quo nam incidunt sit placeat atque, quaerat, nihil nostrum vero fugiat ex cum fugit. Delectus, vitae cumque dolores quos aperiam obcaecati impedit numquam perspiciatis totam, officia deleniti quis explicabo magni quasi ea rem saepe soluta maxime laborum iure nesciunt debitis, unde. Officiis et aspernatur fugit alias accusantium eligendi quidem doloribus voluptatibus explicabo id laudantium dolorem, cumque ipsum similique dignissimos deserunt maxime numquam ullam obcaecati. Magnam libero laborum, harum mollitia nemo sunt obcaecati fugit officia accusamus aspernatur temporibus eligendi quod eum, autem, cumque quam tempora, inventore delectus ullam amet eaque accusantium. Expedita voluptatem, maiores ducimus quis, nesciunt neque asperiores, voluptatibus ipsam architecto saepe veniam. A labore vero obcaecati. Nisi quasi, saepe blanditiis optio voluptatibus repudiandae corporis, laboriosam delectus! Dolores eligendi optio incidunt, odio, at quidem harum excepturi voluptatem quibusdam et dignissimos qui ullam officia, perferendis, est voluptates. Amet incidunt sapiente, culpa dolorum fugit debitis. Repellendus ex deserunt, labore quo voluptatum, nemo! Velit repudiandae nemo dicta vel error ducimus nostrum impedit perspiciatis incidunt accusamus delectus minima commodi, sint, fuga, modi quisquam! Nesciunt, veritatis doloremque adipisci fugiat illo qui libero, voluptatibus, inventore voluptatem, sed numquam id temporibus. Porro quasi reprehenderit, velit tempora id enim ab, tempore dolor. Consectetur sint iste, deleniti officiis vel expedita deserunt tempora velit. Minus officia, commodi eaque voluptates? Debitis, provident. Officia atque nostrum blanditiis dolorem possimus nobis quas quaerat at quisquam voluptatum ad, doloribus, accusamus! Iusto saepe itaque voluptates et labore aperiam nulla assumenda fuga, at cum fugit enim hic, tenetur quos quasi officiis nihil dolorem mollitia obcaecati delectus qui! Inventore nostrum, aspernatur velit beatae sequi laborum? Ducimus cupiditate labore at soluta consequatur, accusamus dolore dolores similique enim recusandae. Aperiam aliquam itaque modi consectetur soluta natus eligendi, illo voluptates iure dolorem est qui explicabo dignissimos odio. Minima corrupti, voluptatibus, consequuntur neque nesciunt sunt. Exercitationem expedita tempore, accusamus amet, similique hic ratione reiciendis iusto ullam, ab neque totam?';
    
    textarea.value = lorem;
}
